[package]
name = "unwind"
version = "0.0.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-lang/rust.git"
edition = "2021"
include = [
  '/libunwind/*',
]

[lib]
test = false
bench = false
doc = false

[dependencies]
core = { path = "../core" }
libc = { git = "https://github.com/lewis-revill/libc-cheri.git", branch = "0.2.135-rustc-patches", features = ['rustc-dep-of-std'], default-features = false }
compiler_builtins = { git = "https://github.com/lewis-revill/compiler-builtins-cheri.git", branch = "ljr-cheri-0.1.73" }
cfg-if = "0.1.8"

[build-dependencies]
cc = "=1.0.73"

[features]

# Only applies for Linux and Fuchsia targets
# Static link to the in-tree build of llvm libunwind
llvm-libunwind = []

# Only applies for Linux and Fuchsia targets
# If crt-static is enabled, static link to `libunwind.a` provided by system
# If crt-static is disabled, dynamic link to `libunwind.so` provided by system
system-llvm-libunwind = []
