[package]
name = "rustc_llvm"
version = "0.0.0"
edition = "2021"

[features]
static-libstdcpp = []
emscripten = []

[dependencies]
libc = { git = "https://github.com/lewis-revill/libc-cheri.git", branch = "0.2.135-rustc-patches" }

[build-dependencies]
cc = "1.0.69"
